# Generated by Django 4.2.6 on 2023-10-31 04:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="phonenumber",
            field=models.IntegerField(),
        ),
    ]
