# Generated by Django 4.2.6 on 2023-10-31 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_alter_student_phonenumber"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "emp_id",
                    models.CharField(
                        help_text="Employee ID",
                        max_length=4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ename", models.CharField(max_length=50)),
                ("post", models.CharField(max_length=20)),
                ("salary", models.IntegerField()),
            ],
        ),
    ]
